apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: astros
  name: astros
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  selector:
    matchLabels:
      run: astros
  template:
    metadata:
      labels:
        run: astros
    spec:
      containers:
      - image: krudisar/astros:v1
        imagePullPolicy: Always
        name: astros
        ports:
        - containerPort: 5000
          protocol: TCP
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
